In [2]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9])
new_array = array.reshape(3, 3)
print(new_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array = np.array(input().split(), dtype=int)
new_array = array.reshape(3,3)
print(new_array)